# src/Anneaux/PortailBundle/Resources/config/routing.yml
homepage:
  pattern: /
  defaults:
    _controller: PortailBundle:Site:index

cdr_index:
  pattern:  /ressources
  defaults: 
    _controller: PortailBundle:CDR:index

cdr_images:
  pattern:  /ressources/images
  defaults: 
    _controller: PortailBundle:CDR:images

cdr_imageShow:
  pattern:  /ressources/images/{id}
  defaults: 
    _controller: PortailBundle:CDR:imageShow

blog_index:
  pattern:  /blog
  defaults: 
    _controller: PortailBundle:Article:index

blog_show:
  pattern:  /blog/{slug}
  defaults:
    _controller: PortailBundle:Article:show
  requirements:
    _method:  GET

blog_search:
  pattern:  /blog/search/{slug}
  defaults:
    _controller: PortailBundle:Article:search
  requirements:
    _method:  GET
