parameters:
#    portail.example.class: Anneaux\PortailBundle\Example

services:
#    portail.example:
#        class: %portail.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
